// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXWiJ4qwjwMfugXow3qinDklaULxPVJk',
    appId: '1:235607417186:web:85e3e6f6f86da6cae30c3b',
    messagingSenderId: '235607417186',
    projectId: 'facebook-2a8be',
    authDomain: 'facebook-2a8be.firebaseapp.com',
    storageBucket: 'facebook-2a8be.firebasestorage.app',
    measurementId: 'G-140JF17TQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHre85zIPcBXFikVw9RkUTVii-4g2cxME',
    appId: '1:235607417186:android:d4a69522dfbcf7c5e30c3b',
    messagingSenderId: '235607417186',
    projectId: 'facebook-2a8be',
    storageBucket: 'facebook-2a8be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB41VKG2hXNhcbQDN5zlBSXpcapi1pBwaw',
    appId: '1:235607417186:ios:636c84161f093131e30c3b',
    messagingSenderId: '235607417186',
    projectId: 'facebook-2a8be',
    storageBucket: 'facebook-2a8be.firebasestorage.app',
    androidClientId: '235607417186-u28ttvc3sd0c6snk7ctqe8t4bphaiq7u.apps.googleusercontent.com',
    iosClientId: '235607417186-97j8bjajgji8ihoj1atfpc8qcu507j9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB41VKG2hXNhcbQDN5zlBSXpcapi1pBwaw',
    appId: '1:235607417186:ios:636c84161f093131e30c3b',
    messagingSenderId: '235607417186',
    projectId: 'facebook-2a8be',
    storageBucket: 'facebook-2a8be.firebasestorage.app',
    androidClientId: '235607417186-u28ttvc3sd0c6snk7ctqe8t4bphaiq7u.apps.googleusercontent.com',
    iosClientId: '235607417186-97j8bjajgji8ihoj1atfpc8qcu507j9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookClone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqXWiJ4qwjwMfugXow3qinDklaULxPVJk',
    appId: '1:235607417186:web:89c50a4778abf92fe30c3b',
    messagingSenderId: '235607417186',
    projectId: 'facebook-2a8be',
    authDomain: 'facebook-2a8be.firebaseapp.com',
    storageBucket: 'facebook-2a8be.firebasestorage.app',
    measurementId: 'G-T5F85X1G3J',
  );
}
